# render.yaml

services:
  # Base de données PostgreSQL
  - type: postgres # <-- LE TYPE CORRECT EST 'postgres'
    name: invitation-db-postgres
    region: frankfurt

  # Application Web Flask
  - type: web
    name: invitation-app-flask
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt && flask db upgrade"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: postgres # <-- CORRECTION ICI
          name: invitation-db-postgres
          property: connectionString
      - key: FLASK_APP
        value: app.py
      - key: PYTHON_VERSION
        value: "3.11.0"
      - fromGroup: app-secrets

# Groupe de variables secrètes
envVarGroups:
  - name: app-secrets
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: EMAIL_USER
        value: "votre.email.reel@gmail.com" # Mettez votre vrai email
      - key: EMAIL_PASS
        value: "votremotdepasseapplication16lettres" # Mettez votre vrai mot de passe