"""Augmentation de la taille de password_hash

Revision ID: 32069a72d294
Revises: eff6b0fe46c0
Create Date: 2025-07-20 02:46:47.062142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32069a72d294'
down_revision = 'eff6b0fe46c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
