"""Création de la base de données initiale complète

Revision ID: ca7c603b165f
Revises: 
Create Date: 2025-07-21 11:54:22.198810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca7c603b165f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('service_demandeur', sa.String(length=100), nullable=False),
    sa.Column('responsable_email', sa.String(length=120), nullable=False),
    sa.Column('nombre_repas', sa.Integer(), nullable=True),
    sa.Column('nombre_desserts', sa.Integer(), nullable=True),
    sa.Column('nombre_limonades', sa.Integer(), nullable=True),
    sa.Column('nombre_boissons_chaudes', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('societe', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('invitation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest')
    op.drop_table('invitation')
    op.drop_table('user')
    # ### end Alembic commands ###
